- hosts: wdcreancil02
  vars:  
    custom_repo: true
  vars_files:
    - ~/RHACCOUNT
  become: yes
  become_method: sudo
  pre_tasks:
    
# tasks:
    - name: download epel
      shell:  wget https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm -O /tmp/epel-release-latest-7.noarch.rpm   
    - name: Install epel
      shell:  yum -y localinstall /tmp/epel*rpm

    - name: install X Window System
      shell: yum -y groupinstall "X Window System"

    - name: install XFCE
      shell: yum -y groupinstall "xfce"

    - name: install Evince
      shell: yum -y install evince

    - name: Install python-pip
      shell: yum install -y python27 python-pip
    - name: install gdown
      shell: pip install gdown  
#     yum:
#       name: python27-python-pip
#       state: latest
    - name: Install python 3.6 and pip
      shell: yum install -y python36 python36-pip

    - name: make localrepo directory
      shell: mkdir -p /opt/ancillary_local
    - name: make OpenOffice directory
      shell: mkdir -p /opt/ancillary_local/OO416
    - name: make Sublime3 directory
      shell: mkdir -p /opt/ancillary_local/Sublime3
    - name: make Sublime3 install directory
      shell: mkdir -p /usr/local/sublime
    - name: make stattransfer14 install directory
      shell: mkdir -p /usr/local/StatTransfer14


    - name: Extract repo to destination point
      shell:  tar xvf /tmp/ancilRH7_repo.tar.gz -C /opt/ancillary_local
    - name: Extract OpenOffice 4.1.6 
      shell:  tar xvf /opt/ancillary_local/Apache_OpenOffice_4.1.6_Linux_x86-64_install-rpm_en-US.tar.gz -C /opt/ancillary_local/OO416 
    - name: install bz2
      yum:
        name: bzip2

    - name: Extract Sublime3 
      shell:  tar xvf /opt/ancillary_local/sublime_text_3_build_3207_x64.tar.bz2 -C /opt/ancillary_local/Sublime3

    - name: Extract Sublime3 to install dir
      shell:  tar xvf /opt/ancillary_local/sublime_text_3_build_3207_x64.tar.bz2 -C /usr/local/sublime 

  roles:
    - umask
#   - devtools
    - devtools7
#   - open_office
    - open_officeRH7
#   - evince
#   See line #39 (evince)
#   - stattransfer
    - stattransfer14
#   - sublime
    - sublime3
#   - ultra-edit
    - ultra-editRH7
    - texliveRH7

  post_tasks:
#   - name: Install texlive
#     yum:
#       name: texlive2016
#       state: present

#   - name: remove RHEL7.5
#     command:  "/usr/bin/subscription-manager remove --all"
#   - name: unregister RHEL7.5
#     command:  "/usr/bin/subscription-manager unregister"
#   - name: clean RHEL7.5
#     command:  "/usr/bin/subscription-manager clean"
