---
- name: Install Python RPM dependencies
  yum:
    name: "{{ item }}"
    state: present
    disable_gpg_check: yes
  with_items: "{{ python_dep_packages }}"
  tags:
    - python-libs

- name: Install Python packages for 27
  pip:
    name: "{{ python_packages }}"
    state: "{{ python_package_mode }}"
    executable: "{{ python_pip_bin }}"
  when: install_python
  tags:
    - python-libs

- name: Install beakerx
  command: beakerx-install
  when: install_python
  tags:
    - python-libs

- name: Install Python packages for 35
  pip:
    name: "{{ python3_packages }}"
    state: "{{ python_package_mode }}"
    executable: "{{ python3_pip_bin }}"
  when: install_python
  tags:
    - python-libs
