# main.yml - Install Python 3.4, either from a repo or a built RPM
---
- name: Install Python34 from repo
  yum:
    name: python34
    state: present

- name: Install setup tools
  yum:
    name: python34-setuptools
    state: present

- name: Install pip
  easy_install:
    name: pip
    executable: easy_install-3.4
