#! /usr/bin/expect

# run the actual installer bin
spawn {{mathlm_install_directory}}/{{mathlm_unzipped_folder}}/{{mathlm_install_package_name}}

# set a 2 minute timeout
set timeout 20

expect "Enter \'c\' to continue" { send "c\r" }
expect "activation key" { send "{{mathlm_activation_key}}\r" }
expect "MathLM password" {send "{{mathlm_password}}\r"}
expect "additional activation key" {send "n\r"}
expect "MathLM directory" {send "\r"}
interact

expect eof

